### ISSUE TITLE
Why transacted hollowing doesn't need to do image relocation?

### ISSUE THREAD

**Issue by EddieIvan01** [hasherezade/transacted_hollowing#3]
Hello hasherezade

https://github.com/hasherezade/transacted_hollowing/blob/main/main.cpp#L60
https://github.com/m0n0ph1/Process-Hollowing/blob/master/sourcecode/ProcessHollowing/ProcessHollowing.cpp#L162

I wonder why it is different with Process Hollowing (which needs to do relocation)

**Comment by hasherezade** [comment]
hi!
The reason is, in Transacted Hollowing the payload is mapped as IMAGE - it means the native functions are aware of its PE header, and can make a use out of it. If it has a relocation table, it will be recognized, and the image is going to be automatically relocated. First, `NtMapViewOfSection` will try to map it at its original base, that is set in the header. If it was impossible, the image is still mapped, but on a different base - the status `STATUS_IMAGE_NOT_AT_BASE` informs about it. In such case, the image that has a valid import table, will be automatically relocated on `ResumeThread`.

**Comment by EddieIvan01** [comment]
Got it, thx!
